#!/bin/bash -x
set -e

if [ ! -d /ceph/.git ] ; then
  echo "ERROR: no git repo in /ceph"
  exit 1
fi

if [ -z $BUILD_THREADS ] ; then
  BUILD_THREADS=4
fi

if [ -z $CLEAN ] ; then
  CLEAN=false
fi

if [ "$CLEAN" = "true" ] ; then
  git submodule foreach 'git clean -fdx && git reset --hard'
  git clean -fdx && git reset --hard
  git submodule update --init --recursive
  rm -r build/ || true
  mkdir -p build
  cd build
  cmake ..
fi

cd /ceph/build
make -j$BUILD_THREADS
make install DESTDIR=./install

exit 0
