#!/bin/bash
set -e
set -x

. build-common

if [ "$RECONFIGURE" = "true" ] || [ "$CLEAN" = "true" ] ; then
  ./autogen.sh
  autoconf || true
  ./configure --prefix=/usr $CONFIGURE_FLAGS
fi

make -j$BUILD_THREADS
make install DESTDIR=`pwd`/install

export CEPH_INSTALL_PATH=/ceph/install
. generate_daemon_image

exit 0
