#!/bin/bash
set -e
set -x

export CONFIGURE_FLAGS="--disable-static --with-mantle --without-rbd --without-rgw --without-debug $CONFIGURE_FLAGS"
export CFLAGS="-Os -s"
export CXXFLAGS="-Os -s"
export CC="ccache gcc"
export CXX="ccache g++"
export LUA_LIBS="-llua5.2"

build-make

exit 0
