#!/bin/bash
set -e
set -x

export CONFIGURE_FLAGS='--with-librocksdb-static \
  --target=x86_64 --host=x86_64 --build=x86_64 \
  --disable-static --with-debug --with-mantle'
export CC="ccache gcc"
export CFLAGS="-Wall -g"
export CXX="ccache g++"
export CXXFLAGS="-Wall -g"
export LUA_LIBS="-llua5.2"

build-make

exit 0
